postogramm/bars/urls.py
from django.urls import path
from . import views

app_name = 'bars'

urlpatterns = [
    path('', views.Main.as_view(), name='main'),
    path('bar/', views.Bar.as_view(), name='bar'),
    path('bar_chat/', views.BarChat.as_view(), name='bar_chat'),
    path('photo_bar/', views.PhotoBar.as_view(), name='photo_bar'),
    path('add_bar/', views.AddBar.as_view(), name='add_bar'),
    path('add_photo_bar/', views.AddPhotoBar.as_view(), name='add_photo_bar')
]

postogramm/postogramm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bars.urls', namespace='bars')),
    path('users/', include('users.urls', namespace='users')),
    path('private_chats/', include('private_chats.urls', namespace='private_chats'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postogramm/private_chats/urls.py
from django.urls import path
from . import views

app_name = 'private_chats'

urlpatterns = [
    path('main_chats/', views.MyChats.as_view(), name='main_chats'),
    path('main_chats/chat/', views.Chat.as_view(), name='chat'),
    path('main_chats/chat/add_participants_chat/', views.ParticipantsChat.as_view(), name='add_participants_chat'),
    path('main_chats/add_chat/', views.AddChat.as_view(), name='add_chat')
]

postogramm/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.Profile.as_view(), name='profile'),
    path('register/', views.RegisterUsers, name='register'),
    path('register/login/', views.LoginUser.as_view(), name='login')
]

postogramm/bars/models.py
from django.db import models
from users.models import Users


class Category(models.Model):
    cat_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.cat_name


class Bars(models.Model):
    owner_bar = models.ForeignKey(
        to=Users,
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    img = models.ImageField(upload_to='bars_img')
    bar_category = models.ManyToManyField(
        to=Category,
        db_index=True
    )
    public = models.BooleanField(
        default=True,
        db_index=True
    )

    def __str__(self):
        return self.name
    
    
class ImgBar(models.Model):
    where_img = models.ForeignKey(
        to=Bars,
        on_delete=models.CASCADE
    )
    img = models.ImageField(upload_to='bars_img')
    name_img = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name_img
    
    
class BarMessages(models.Model):
    where_message = models.ForeignKey(
        to=Bars,
        on_delete=models.CASCADE
    )
    owner_message = models.ForeignKey(
        to=Users,
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100)
    content = models.CharField(max_length=100)
    create_time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name


class FavoriteBar(models.Model):
    whose_bar = models.ForeignKey(
        to=Users,
        on_delete=models.CASCADE
    )
    bar = models.ManyToManyField(
        to=Bars,
        related_name='favorite_bar',
        blank=True,
        null=True
    )

postogramm/bars/forms.py
from django import forms
from .models import BarMessages, Bars, ImgBar


class AddMessage(forms.ModelForm):
    class Meta:
        model = BarMessages
        fields = [
            'name',
            'content'
        ]
        
        
class AddBarsForm(forms.ModelForm):
    class Meta:
        model = Bars
        fields = [
            'img',
            'name',
            'description',
            'bar_category'
        ]
        
        
class AddPhotoBarForm(forms.ModelForm):
    class Meta:
        model = ImgBar
        fields = [
            'img',
            'name_img'
        ]

postogramm/bars/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import DetailView, ListView, CreateView
from .models import Bars, ImgBar, FavoriteBar, BarMessages
from .forms import AddMessage, AddBarsForm, AddPhotoBarForm
from django.urls import reverse, reverse_lazy
from users.models import Users


class Main(View):
    def get(self, request):
        bars = Bars.objects.filter(public=True)
        
        return render(request, 'bars/main.html', {'bars': bars})
    
    def post(self, request):
        bars = Bars.objects.filter(public=True)
        button = request.POST['button']
        if button == 'filter':
            bar_cat = request.POST['bar_category']
            if bar_cat == 'all':
                pass
            else:
                bars = Bars.objects.filter(bar_category=bar_cat)
        else:
            request.session['pk_bar'] = button
            return redirect('bar/')
        
        return render(request, 'bars/main.html', {'bars': bars})

    
class Bar(View):
    def get(self, request):
        pk_bar = request.session['pk_bar']
        bar = Bars.objects.get(pk=pk_bar)
        
        return render(request, 'bars/bar.html', {'bar': bar})
    
    def post(self, request):
        pk_bar = request.session['pk_bar']
        bar = Bars.objects.get(pk=pk_bar)
        user_pk = self.request.user.pk
        user = Users.objects.get(pk=user_pk)
        if user.user_status_id == 3 or user_pk == bar.owner_bar_id:
            bar.public = False
            bar.save()    
        else:
            pass
        
        return render(request, 'bars/bar.html', {'bar': bar})
    
    
class PhotoBar(ListView):
    model = ImgBar
    template_name = 'bars/photo_bar.html'
    context_object_name = 'photo_bar'
    
    def get_queryset(self):
        pk_bar = self.request.session['pk_bar']
        photo_bar = ImgBar.objects.filter(where_img=pk_bar)
        return photo_bar
    
    
class BarChat(View):
    def get(self, request):
        form = AddMessage
        pk_bar = request.session['pk_bar']
        bar_message = BarMessages.objects.filter(where_message=pk_bar)
        
        return render(request, 'bars/bar_message.html', {'form': form, 'bar_message': bar_message})
    
    def post(self, request):
        form = AddMessage
        pk_bar = request.session['pk_bar']
        bar_message = BarMessages.objects.filter(where_message=pk_bar)
        button = request.POST['button']
        if button == 'add_message':
            BarMessages.objects.create(
                where_message_id=pk_bar,
                owner_message_id=self.request.user.pk,
                name=request.POST['name'],
                content = request.POST['content']
            )
        else:
            message = BarMessages.objects.get(pk=button)
            if message.owner_message_id == self.request.user.pk:
                message.delete()
            else:
                pass
        
        return render(request, 'bars/bar_message.html', {'form': form, 'bar_message': bar_message})
    
    
class AddBar(CreateView):
    template_name = 'bars/add_bar.html'
    form_class = AddBarsForm
    success_url=reverse_lazy('bars:main')
    
    def form_valid(self, form):
        try:
            user_pk = self.request.user.pk
            user = Users.objects.get(pk=user_pk)
            if user.user_status_id == 2 or user.user_status_id == 3:
                valid_f = form.save(commit=False)
                valid_f.owner_bar_id = user_pk
            else:
                pass
        except:
            pass
        return super().form_valid(form)
    
    
class AddPhotoBar(CreateView):
    template_name = 'bars/add_photo_bar.html'
    form_class = AddPhotoBarForm
    success_url=reverse_lazy('users:profile')
    
    def form_valid(self, form):
        f_valid = form.save(commit=False)
        f_valid.where_img_id=self.request.session['pk_bar']
        return super().form_valid(form)

postogramm/bars/templates/bars/add_bar.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create bar</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'bars/styles.css' %}">
</head>
<body>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Добавить</button>
    </form>
</body>
</html>

postogramm/bars/templates/bars/add_photo_bar.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add photo bar</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'bars/styles.css' %}">
</head>
<body>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Добавить</button>
    </form>
</body>
</html>

postogramm/bars/templates/bars/bar.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bar</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'bars/styles.css' %}">
</head>
<body>
    <div>
        <p>Владелец бара: {{bar.owner_bar}}</p>
        <img src="{{bar.img.url}}" alt="где фото?">
        <p>Название: {{bar.name}}</p>
        <p>Описание: {{bar.description}}</p>
        <p>Категории:</p>
        {% for cat in bar.bar_category.all %}
        {{cat}}<br>
        {% endfor %}
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            <button type="button">
                <a href="{% url 'bars:bar_chat' %}">Чат бара</a>
            </button>
            <button type="button">
                <a href="{% url 'bars:photo_bar' %}">Фото бара</a>
            </button>
            <button type="submit">Скрыть</button>
        </form>
    </div>
</body>
</html>

postogramm/bars/templates/bars/bar_message.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bar message</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'bars/styles.css' %}">
</head>
<body>
    <div>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button name="button" value="add_message" type="submit">Добавить</button>
        </form>
    </div>
    <br>
    {% for i in bar_message %}
    <br>
    <div>
        <p>От: {{i.owner_message}}</p>
        <p>Название: {{i.name}}</p>
        <p>Описание: {{i.content}}</p>
        <form method="post">
            {% csrf_token %}
            <button name="button" value="{{i.pk}}" type="submit">Удалить</button>
        </form>
    </div>
    {% endfor %}
</body>
</html>

postogramm/bars/templates/bars/main.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'bars/styles.css' %}">
</head>
<body>
    <div>
        <form method="post">
            <select name="bar_category" id="bar_category">
                <option value="1">весело посидеть</option>
                <option value="2">много человек</option>
                <option value="3">мало человек (не больше 4)</option>
                <option value="4">необычные напитки</option>
                <option value="5">для людей с широким кошельком</option>
                <option value="6">для людей с маленьким кошельком</option>
                <option value="all">все категории</option>
            </select>
            {% csrf_token %}
            <button name="button" value="filter" type="submit">Отфильтровать</button>
            <button type="button">
                <a href="{% url 'users:profile' %}">Профиль</a>
            </button>
            <button type="button">
                <a href="{% url 'private_chats:main_chats' %}">Приватные Чаты</a>
            </button>
            <button type="button">
                <a href="{% url 'users:register' %}">Зарегистрироваться</a>
            </button>
        </form>
    </div>
    <br>
    {% for i in bars %}
    <br>
    <div>
        <img src="{{i.img.url}}" alt="где фото?">
        <p>Название бара: {{i.name}}</p>
        <p>Категории:</p>
        {% for cat in i.bar_category.all %}
        {{cat}}<br>
        {% endfor %}
        <form method="post">
            {% csrf_token %}
            <button name="button" value="{{i.pk}}" type="submit">Подробнее</button>
        </form>
    </div>
    {% endfor %}
</body>
</html>

postogramm/bars/templates/bars/photo_bar.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Photo bar</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'bars/styles.css' %}">
</head>
<body>
    {% for i in photo_bar %}
    <br>
    <div>
        <img src="{{i.img.url}}" alt="где фото?">
        <p>Подпись к фотографии: {{i.name_img}}</p>
    </div>
    {% endfor %}
</body>
</html>