postogramm/bars/urls.py
from django.urls import path
from . import views

app_name = 'bars'

urlpatterns = [
    path('', views.Main.as_view(), name='main'),
    path('bar/', views.Bar.as_view(), name='bar'),
    path('bar_chat/', views.BarChat.as_view(), name='bar_chat'),
    path('photo_bar/', views.PhotoBar.as_view(), name='photo_bar'),
    path('add_bar/', views.AddBar.as_view(), name='add_bar'),
    path('add_photo_bar/', views.AddPhotoBar.as_view(), name='add_photo_bar')
]

postogramm/postogramm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bars.urls', namespace='bars')),
    path('users/', include('users.urls', namespace='users')),
    path('private_chats/', include('private_chats.urls', namespace='private_chats'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postogramm/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('profile/', views.Profile.as_view(), name='profile'),
    path('register/', views.RegisterUsers, name='register'),
    path('register/login/', views.LoginUser.as_view(), name='login')
]

postogramm/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Status(models.Model):
    status_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.status_name


class Users(AbstractUser):
    user_status = models.ForeignKey(
        to=Status,
        on_delete=models.CASCADE,
        default=1
    )
    
    def __str__(self):
        return self.username

postogramm/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from users.models import Users


class RegisterUser(UserCreationForm):
    class Meta:
        model = Users
        fields = [
            'username',
            'email',
            'password1',
            'password2'
        ]

postogramm/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Users
from bars.models import Bars
from .forms import RegisterUser
from django.contrib.auth.views import LoginView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import AuthenticationForm


def RegisterUsers(request):
    if request.method == 'POST':
        form = RegisterUser(request.POST)
        if form.is_valid():
            user = form.save()
            user.set_password(request.POST['password1'])
            user.save()
            status = 'Вы успешно зарегистрированы, теперь необходимо войти в аккаунт'
        else:
            status = 'что то пошло не так :('

    else:
        form = RegisterUser()
        status = ''
    
    return render(request, 'users/register.html', {'form': form, 'status': status})


class LoginUser(LoginView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'
    
    def get_success_url(self):
        return reverse_lazy('bars:main')


class Profile(View):
    def get(self, request):
        u = self.request.user.pk
        user = Users.objects.get(pk=u)
        user_bars = Bars.objects.filter(owner_bar=u)
        status = ''
        
        return render(request, 'users/profile.html', {'user': user, 'user_bars': user_bars, 'status': status})
    
    def post(self, request):
        try:
            u = self.request.user.pk
            user = Users.objects.get(pk=u)
            user_bars = Bars.objects.filter(owner_bar=u)
            pk_bar = request.POST['pk_bar']
            action_bar = request.POST['action_bar']
            if action_bar == 'delete':
                Bars.objects.get(pk=pk_bar).img.delete(save=True)
                Bars.objects.get(pk=pk_bar).delete()
            else:
                request.session['pk_bar'] = pk_bar
                return redirect('bars:add_photo_bar')
            status = ''
        except:
            status = 'необходимо зарегистрироватся'
        
        return render(request, 'users/profile.html', {'user': user, 'user_bars': user_bars, 'status': status})

postogramm/users/templates/users/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'bars/styles.css' %}">
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Отправить</button>
    </form>
</body>
</html>

postogramm/users/templates/users/profile.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'bars/styles.css' %}">
</head>
<body>
    <div>
        <h2>Информация о вас:</h2>
        <p>Ник: {{user.username}}</p>
        <p>электронная почта: {{user.email}}</p>
        <p>Ваш статус: {{user.user_status}}</p>
    </div>
    <br>
    <div>
        <h2>ваши бары:</h2>
        <button type="button">
            <a href="{% url 'bars:add_bar' %}">Добавить бар</a>
        </button>
        {% for i in user_bars %}
        <br>
        <div>
            <img src="{{ i.img.url }}" alt="где фото?">
            <p>Название: {{i.name}}</p>
            <p>Описание: {{i.description}}</p>
            <p>Категории:</p>
            {% for cat in i.bar_category.all %}
            {{cat}}<br>
            {% endfor %}
            {% if i.public == True %}
            <p>Бар публичный</p>
            {% else %}
            <p>Бар не публичный</p>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <button name="pk_bar" value="{{i.pk}}" type="submit">Выполнить</button>
                <select name="action_bar" id="action_bar">
                    <option value="add_photo">Добавить фото</option>
                    <option value="delete">Удалить</option>
                </select>
            </form>
        </div>
        {% endfor %}
    </div>
</body>
</html>

postogramm/users/templates/users/register.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'bars/styles.css' %}">
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Зарегистрироваться</button>
        <button type="button">
            <a href="login">Войти в аккаунт</a>
        </button>
    </form>
</body>
</html>